//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public Flat()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int FlatId { get; set; }
        public string FlatSize { get; set; }
        public string FlatDetails { get; set; }
        public string Location { get; set; }
        public int Rent { get; set; }
        public int UserId { get; set; }
        public string FlatImage { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Flat Flats1 { get; set; }
        public virtual Flat Flat1 { get; set; }
        public virtual Flat Flats11 { get; set; }
        public virtual Flat Flat2 { get; set; }
        public virtual Flat Flats12 { get; set; }
        public virtual Flat Flat3 { get; set; }
        public virtual User User { get; set; }
    }
}
